-- ============================================================
-- TRADE SYSTEM v2 — Full Schema
-- Run this FULLY in Supabase SQL Editor
-- ============================================================

-- 1. USERS TABLE (keep existing)
create table if not exists users (
  id         uuid primary key default gen_random_uuid(),
  username   text unique not null,
  password   text not null,
  name       text default '',
  role       text default 'USER' check (role in ('ADMIN','USER')),
  active     boolean default true,
  created_at timestamptz default now()
);

-- 2. TRADERS TABLE (clients)
create table if not exists traders (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  phone      text default '',
  note       text default '',
  active     boolean default true,
  created_by text references users(username) on delete set null,
  created_at timestamptz default now()
);

-- 3. WEEKS TABLE (global weeks, all traders share same weeks)
create table if not exists weeks (
  id         uuid primary key default gen_random_uuid(),
  label      text not null,         -- e.g. "Week 1 | 24 Feb – 28 Feb"
  start_date date,
  end_date   date,
  status     text default 'open',   -- open | settled
  created_by text references users(username) on delete set null,
  created_at timestamptz default now()
);

-- 4. TRADES TABLE (linked to trader + week)
create table if not exists trades (
  id             uuid primary key default gen_random_uuid(),
  trader_id      uuid references traders(id) on delete cascade,
  week_id        uuid references weeks(id) on delete cascade,
  trade_date     text default '',
  action         text default 'BUY',
  qty            numeric default 0,
  price          numeric default 0,
  vol            numeric default 0,
  script         text default '',
  type           text default 'NORMAL',   -- NORMAL | FORWARD
  exchange       text default 'NSE',
  is_settlement  boolean default false,   -- true = auto-generated by settlement
  sort_order     integer default 0,
  created_at     timestamptz default now()
);

-- 5. SETTLEMENT RATES (per week, per script)
create table if not exists settlement_rates (
  id         uuid primary key default gen_random_uuid(),
  week_id    uuid references weeks(id) on delete cascade,
  script     text not null,
  rate       numeric not null,
  exchange   text default 'NSE',
  lot_qty    numeric default 1,
  created_at timestamptz default now(),
  unique(week_id, script)
);

-- 6. SETTINGS (NSE rate + MCX scripts, per user)
create table if not exists user_settings (
  username    text primary key references users(username) on delete cascade,
  nse_rate    numeric default 3000,
  mcx_scripts jsonb default '[]',
  updated_at  timestamptz default now()
);

-- Disable Row Level Security (simple setup)
alter table users            disable row level security;
alter table traders          disable row level security;
alter table weeks            disable row level security;
alter table trades           disable row level security;
alter table settlement_rates disable row level security;
alter table user_settings    disable row level security;

-- Insert default admin
insert into users (username, password, name, role, active)
values ('admin', 'admin123', 'Administrator', 'ADMIN', true)
on conflict (username) do nothing;

-- ============================================================
-- DONE! Run this in SQL Editor → all tables ready
-- ============================================================
